// Partners Data
export const partners = [
  {
    id: 'emerchantpay',
    name: 'emerchantpay',
    type: 'Acquirer',
    status: 'Active',
    contact: 'Suzanne',
    website: 'https://www.emerchantpay.com/',
    countries: ['EU (EEA)'],
    paymentMethods: ['Visa/Mastercard'],
    industries: ['Gambling (EU licensed)', 'FX/CFD', 'Adult'],
    settlementCurrencies: ['EUR', 'GBP', 'USD', 'AUD', 'CAD'],
    settlementTimeframe: 'T+2',
    revenueShare: '30%',
    notes: 'Currently have 5 clients processing through them.',
  },
];

// Deals Data
export const deals = [
  {
    id: 'lfa-international',
    name: 'LFA International Ltd.',
    industry: 'Prop Trading / Gaming',
    status: 'Live',
    monthlyVolume: 'TBD',
    potentialRevenue: '30% of buy rate',
    priority: 'High',
    partnerId: 'emerchantpay',
    description: 'Prop trading firm / gaming operator.',
  },
  {
    id: 'yellow-social',
    name: 'Yellow Social Interactive Ltd.',
    industry: 'Social Gaming / Casino',
    status: 'Live',
    monthlyVolume: 'TBD',
    potentialRevenue: '30% of buy rate',
    priority: 'High',
    partnerId: 'emerchantpay',
    description: 'Social gaming/casino operator.',
  },
  {
    id: 'b-two',
    name: 'B-two Operations Ltd.',
    industry: 'Gaming',
    status: 'Live',
    monthlyVolume: 'TBD',
    potentialRevenue: '30% of buy rate',
    priority: 'Medium',
    partnerId: 'emerchantpay',
    description: 'Gaming operator.',
  },
  {
    id: 'globex',
    name: 'Globex SARL',
    industry: 'FX / CFD',
    status: 'Live',
    monthlyVolume: 'TBD',
    potentialRevenue: '30% of buy rate',
    priority: 'Medium',
    partnerId: 'emerchantpay',
    description: 'FX/CFD trading firm.',
  },
  {
    id: 'play-spree',
    name: 'Play Spree Ltd.',
    industry: 'Online Casino',
    status: 'Live',
    monthlyVolume: 'TBD',
    potentialRevenue: '30% of buy rate',
    priority: 'High',
    partnerId: 'emerchantpay',
    description: 'Online casino/gaming operator.',
  },
];
