// Partners Data
export const partners = [
  {
    id: 'emerchantpay',
    name: 'emerchantpay',
    type: 'Card Acquirer',
    status: 'Active',
    contact: 'Suzanne',
    website: 'https://www.emerchantpay.com/',
    countries: ['EU (EEA)'],
    paymentMethods: ['Visa', 'Mastercard'],
    industries: ['EU Licensed Gambling', 'FX Trading', 'Adult'],
    settlementCurrencies: ['EUR', 'GBP', 'USD', 'AUD', 'CAD'],
    settlementTimeframe: 'T+2',
    rollingReserve: 'Flexible - depends on client',
    revenueShare: '30%',
    notes: 'First partner in CRM. Strong relationship with Suzanne. 5 active clients processing.',
    keyStrengths: [
      '5 active clients already processing',
      'Strong in EU licensed Gambling, FX, Adult',
      'Multiple settlement currencies',
      'Fast T+2 settlement'
    ],
    clients: [
      'LFA International Ltd.',
      'Yellow Social Interactive Ltd.',
      'B-two Operations Ltd.',
      'Globex SARL',
      'Play Spree Ltd.'
    ],
    lastUpdated: '2026-02-27',
    followUpDate: null,
    followUpNotes: null
  },
];

// Deals Data
export const deals = [
  {
    id: 'lfa-international',
    name: 'LFA International Ltd.',
    industry: 'Prop Trading / Gaming',
    status: 'Live',
    stage: 'Processing',
    monthlyVolume: '€1M+',
    potentialRevenue: '30% of buy rate',
    priority: 'High',
    partnerId: 'emerchantpay',
    partnerName: 'emerchantpay',
    description: 'Prop trading firm / gaming operator. Currently processing through emerchantpay.',
    contactName: null,
    contactEmail: null,
    contactTelegram: null,
    nextFollowUp: null,
    notes: 'Active client processing through emerchantpay.',
    dateOpened: '2025-01-01',
    dateClosed: null
  },
  {
    id: 'yellow-social',
    name: 'Yellow Social Interactive Ltd.',
    industry: 'Social Gaming / Casino',
    status: 'Live',
    stage: 'Processing',
    monthlyVolume: '€1M+',
    potentialRevenue: '30% of buy rate',
    priority: 'High',
    partnerId: 'emerchantpay',
    partnerName: 'emerchantpay',
    description: 'Social gaming/casino operator. Currently processing through emerchantpay.',
    contactName: null,
    contactEmail: null,
    contactTelegram: null,
    nextFollowUp: null,
    notes: 'Active client processing through emerchantpay.',
    dateOpened: '2025-01-01',
    dateClosed: null
  },
  {
    id: 'b-two',
    name: 'B-two Operations Ltd.',
    industry: 'Gaming',
    status: 'Live',
    stage: 'Processing',
    monthlyVolume: '€1M+',
    potentialRevenue: '30% of buy rate',
    priority: 'Medium',
    partnerId: 'emerchantpay',
    partnerName: 'emerchantpay',
    description: 'Gaming operator. Currently processing through emerchantpay.',
    contactName: null,
    contactEmail: null,
    contactTelegram: null,
    nextFollowUp: null,
    notes: 'Active client processing through emerchantpay.',
    dateOpened: '2025-01-01',
    dateClosed: null
  },
  {
    id: 'globex',
    name: 'Globex SARL',
    industry: 'FX / CFD',
    status: 'Live',
    stage: 'Processing',
    monthlyVolume: '€1M+',
    potentialRevenue: '30% of buy rate',
    priority: 'Medium',
    partnerId: 'emerchantpay',
    partnerName: 'emerchantpay',
    description: 'FX/CFD trading firm. Currently processing through emerchantpay.',
    contactName: null,
    contactEmail: null,
    contactTelegram: null,
    nextFollowUp: null,
    notes: 'Active client processing through emerchantpay.',
    dateOpened: '2025-01-01',
    dateClosed: null
  },
  {
    id: 'play-spree',
    name: 'Play Spree Ltd.',
    industry: 'Online Casino',
    status: 'Live',
    stage: 'Processing',
    monthlyVolume: '€1M+',
    potentialRevenue: '30% of buy rate',
    priority: 'High',
    partnerId: 'emerchantpay',
    partnerName: 'emerchantpay',
    description: 'Online casino/gaming operator. Currently processing through emerchantpay.',
    contactName: null,
    contactEmail: null,
    contactTelegram: null,
    nextFollowUp: null,
    notes: 'Active client processing through emerchantpay.',
    dateOpened: '2025-01-01',
    dateClosed: null
  },
];
